import { SliderOptions } from '../slider/utils/types';
declare class Demo {
    private sliderElement;
    private panelElement;
    private slider;
    private maxValueInput;
    private minValueInput;
    private lowValueInput;
    private highValueInput;
    private stepInput;
    private isRangeInput;
    private isTipsHiddenInput;
    private isVerticalInput;
    constructor(sliderElement: JQuery, panelElement: HTMLElement, sliderOptions: SliderOptions);
    private init;
    private handleSliderChange;
    private initMaxValueInput;
    private handleMaxValueChange;
    private initMinValueInput;
    private handleMinValueChange;
    private initLowValueInput;
    private handleLowValueChange;
    private initHighValueInput;
    private handleHighValueChange;
    private initStepInput;
    private handleStepChange;
    private initRangeInput;
    private handleRangeChange;
    private initTipsHiddenInput;
    private handleTipsHiddenInputChange;
    private initIsVerticalInput;
    private handleIsVerticalInputChange;
}
export default Demo;
