import Publisher from '../publisher/Publisher';
import { modelOptions } from '../utils/types';
declare class Model extends Publisher {
    private isRange;
    private maxValue;
    private minValue;
    private lowValue;
    private highValue;
    private step;
    constructor(options: modelOptions);
    getRangeStatus(): boolean;
    setRangeMode(isRange: boolean): void;
    getMaxValue(): number;
    setMaxValue(value: number): void;
    getMinValue(): number;
    setMinValue(value: number): void;
    getLowValue(): number;
    getLowValueInPercent(): number;
    setLowValue(value: number): void;
    setLowValueByPercent(valueInPercent: number): void;
    getHighValue(): number;
    getHighValueInPercent(): number;
    setHighValueByPercent(valueInPercent: number): void;
    setHighValue(value: number): void;
    getStep(): number;
    setStep(value: number): void;
    splitIntervalByStep(divisionsAmount: number): Map<number, number>;
    private init;
    private validateValue;
    private validateValueInPercent;
    private convertPercentToValue;
    private convertValueToPercent;
}
export default Model;
