import { Orientation } from '../../../utils/types';
import { UpdateViewOptions, ViewOptions } from '../../types';
import ViewComponent from '../ViewComponent';
declare class View extends ViewComponent {
    private strip;
    private range;
    private scale;
    private orientation;
    private orientationBehavior;
    private runnersAndTips;
    private isTipsExists;
    constructor(parentNode: HTMLElement, options: ViewOptions);
    deleteTips(): void;
    createTips(): void;
    getTipsExistStatus(): boolean;
    getOrientation(): Orientation;
    setOrientation(orientation: Orientation): void;
    computeDivisionsAmountBySize(): number;
    updateView({ runnersPositions, tipsValues, scalePositions, isRange, }: UpdateViewOptions): void;
    private init;
    private deleteTip;
    private createTip;
    private setRange;
    private changeModeToRange;
    private changeModeToSingle;
    private setScale;
    private getRunnersAmount;
    private setRunnerPosition;
    private getRunnerPosition;
    private setTipPosition;
    private setTipText;
    private addHandlers;
    private setRunnerToCurrent;
    private handleRunnerDrag;
    private handleSliderClick;
    private handleResize;
    private updateViewForInterval;
    private updateAllTipsPositionAndText;
    private updateViewForSingleRunner;
    private joinTips;
}
export default View;
